"""3D activity smoke checks. Run while npm run dev is serving on port 5173."""
import os
import math
from playwright.sync_api import sync_playwright, expect
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/snap/bin/chromium'),headless=True,args=['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'])
    page=browser.new_page(viewport={'width':1440,'height':1100})
    errors=[]
    page.on('pageerror',lambda e:(errors.append(e.stack),print(e.stack,flush=True)))
    page.goto('http://127.0.0.1:5173',wait_until='networkidle')
    def start(id):
        page.locator('.material-card.'+id).click()
        page.get_by_role('button',name='Begin the activity').click()
        page.get_by_role('button',name='3D',exact=True).click()
        expect(page.locator('.activity-stage canvas')).to_be_visible(timeout=15000)
        page.wait_for_timeout(700)
    def switch(d): page.get_by_role('button',name=d,exact=True).click()
    def leave():page.get_by_role('button',name='Back to the classroom').click()
    def click_world(point,camera,target):
        # Project the known mesh position through the same camera to exercise raycasting.
        r=page.locator('.activity-stage canvas').bounding_box()
        def norm(v):
            length=math.sqrt(sum(x*x for x in v))
            return [x/length for x in v]
        def cross(a,b):return [a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]
        def dot(a,b):return sum(x*y for x,y in zip(a,b))
        forward=norm([t-c for t,c in zip(target,camera)])
        right=norm(cross(forward,[0,1,0]))
        up=cross(right,forward)
        relative=[v-c for v,c in zip(point,camera)]
        scale=r['height']/(2*math.tan(math.radians(20))*dot(relative,forward))
        xy={'x':r['x']+r['width']/2+dot(relative,right)*scale,'y':r['y']+r['height']/2-dot(relative,up)*scale}
        page.mouse.click(xy['x'],xy['y'])
    start('pink-tower')
    click_world([-2.65,.18,-1.7],[6,7,10],[0,1.2,0])
    expect(page.get_by_role('button',name='Select cube 4,')).to_have_attribute('aria-pressed','true')
    click_world([1.2,.08,0],[6,7,10],[0,1.2,0])
    switch('2D')
    expect(page.locator('.stack-cube')).to_have_count(1)
    switch('3D')
    page.get_by_role('button',name='Lift the top cube back').click()
    for n in range(10,0,-1):
        page.get_by_role('button',name=f'Select cube {n},').click()
        page.get_by_role('button',name='Place selected cube in the center').click()
    expect(page.get_by_role('status')).to_contain_text('Your tower is complete')
    page.screenshot(path='/tmp/montessori-3d-tower.png',full_page=True)
    switch('2D')
    expect(page.locator('.stack-cube')).to_have_count(10)
    leave()
    start('cylinder-blocks')
    click_world([-2.925,.555,-.9],[4,6,8],[0,.45,0])
    page.get_by_text('Controls for each cylinder and socket').click()
    expect(page.get_by_role('button',name='Select cylinder 1',exact=True)).to_be_visible()
    for n in range(2,11):page.get_by_role('button',name=f'Lift cylinder {n}',exact=True).click()
    page.screenshot(path='/tmp/montessori-3d-cylinders.png',full_page=True)
    for n in range(1,11):
        page.get_by_role('button',name=f'Select cylinder {n}',exact=True).click()
        page.get_by_role('button',name=f'Try socket {n}',exact=True).click()
    expect(page.get_by_role('status')).to_contain_text('Every cylinder is back')
    switch('2D')
    expect(page.get_by_role('status')).to_contain_text('Every cylinder is back')
    leave()
    start('color-tablets')
    click_world([-2.65,.2,-1.3],[4,6,7],[0,.45,0])
    expect(page.get_by_role('button',name='Choose red tablet one')).to_have_attribute('aria-pressed','true')
    page.get_by_role('button',name='Choose red tablet two').click()
    switch('2D')
    expect(page.locator('.tablet-pair')).to_have_count(1)
    switch('3D')
    for c in ['yellow','blue']:
        for n in ['one','two']:page.get_by_role('button',name=f'Choose {c} tablet {n}').click()
    expect(page.get_by_role('status')).to_contain_text('Each color has a companion')
    page.screenshot(path='/tmp/montessori-3d-colors.png',full_page=True)
    leave()
    start('dressing-frame')
    click_world([-.035,.31,-1.23],[3.5,6,5],[0,.45,0])
    expect(page.get_by_role('button',name='Close button 1')).to_be_visible()
    for n in range(2,5):page.get_by_role('button',name=f'Open button {n}').click()
    page.get_by_role('button',name='Separate the fabric').click()
    page.screenshot(path='/tmp/montessori-3d-dressing.png',full_page=True)
    switch('2D')
    expect(page.locator('.fabric-open')).to_have_count(1)
    switch('3D')
    page.get_by_role('button',name='Bring the fabric together').click()
    for n in range(1,5):page.get_by_role('button',name=f'Close button {n}').click()
    expect(page.get_by_role('status')).to_contain_text('every button is fastened')
    leave()
    start('pouring')
    click_world([-1.43,.6,0],[4.5,4.8,6.5],[0,.7,0])
    expect(page.get_by_role('button',name='Return pitcher to tray')).to_be_visible()
    click_world([1.1,.7,0],[4.5,4.8,6.5],[0,.7,0])
    expect(page.get_by_role('button',name='Move back over the tray')).to_be_visible()
    page.get_by_role('slider').fill('50')
    page.wait_for_timeout(800)
    page.screenshot(path='/tmp/montessori-3d-pouring.png',full_page=True)
    switch('2D')
    expect(page.get_by_role('slider')).to_have_value('50')
    switch('3D')
    page.get_by_role('slider').fill('80')
    expect(page.get_by_text('The pitcher is empty. Bring it upright and return it to the tray.')).to_be_visible(timeout=10000)
    page.get_by_role('button',name='Bring the pitcher upright').click()
    page.get_by_role('button',name='Return pitcher to tray').click()
    expect(page.get_by_role('status')).to_contain_text('The water has been poured')
    page.get_by_role('button',name='Start again',exact=True).click()
    expect(page.get_by_role('status')).not_to_contain_text('The water has been poured')
    expect(page.get_by_role('slider')).to_have_value('0')
    leave()
    mobile=browser.new_page(viewport={'width':390,'height':844},is_mobile=True,has_touch=True)
    mobile.on('pageerror',lambda e:errors.append(e.stack))
    mobile.goto('http://127.0.0.1:5173',wait_until='networkidle')
    for id in ['pink-tower','cylinder-blocks','color-tablets','dressing-frame','pouring']:
        mobile.locator('.material-card.'+id).tap()
        mobile.get_by_role('button',name='Begin the activity').tap()
        mobile.get_by_role('button',name='3D',exact=True).tap()
        expect(mobile.locator('.activity-stage canvas')).to_be_visible()
        assert mobile.evaluate('document.documentElement.scrollWidth<=innerWidth'), id
        mobile.get_by_role('button',name='2D',exact=True).tap()
        mobile.get_by_role('button',name='Back to the classroom').tap()
    assert not errors,'\n'.join(errors)
    print('PASS: all five 3D renderers, direct mesh selection, completion, preserved state across 2D/3D, reset, mobile switching, and no runtime errors')
    browser.close()
