"""Toddler activities and remembered school-access checks on the Pages build."""
import os
from playwright.sync_api import sync_playwright,expect
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/snap/bin/chromium'),headless=True,args=['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'])
    page=browser.new_page(viewport={'width':1440,'height':1100})
    errors=[]
    page.on('pageerror',lambda e:errors.append(e.stack))
    page.goto('http://127.0.0.1:5173/',wait_until='networkidle')
    page.get_by_label('YOUR LEARNING ENVIRONMENT').select_option('18m-3y')
    expect(page.locator('.material-card')).to_have_count(3)
    expect(page.get_by_text('THE TODDLER COMMUNITY',exact=True)).to_be_visible()
    page.wait_for_timeout(800)
    page.screenshot(path='/tmp/montessori-toddler-room.png',full_page=True)
    page.locator('.material-card.transferring').click()
    page.get_by_role('button',name='Begin the activity').click()
    for n in range(1,7):
        page.get_by_role('button',name=f'Select object {n}',exact=True).click()
        page.get_by_role('button',name='Place in right bowl',exact=True).focus()
        page.keyboard.press('Enter')
    expect(page.get_by_role('status')).to_contain_text('The objects are together')
    page.get_by_role('button',name='3D',exact=True).click()
    expect(page.locator('.activity-stage canvas')).to_be_visible(timeout=15000)
    expect(page.get_by_role('status')).to_contain_text('The objects are together')
    page.get_by_role('button',name='Start again',exact=True).click()
    page.get_by_role('button',name='Object 1 · left',exact=True).click()
    page.get_by_role('button',name='Place in right bowl',exact=True).click()
    expect(page.get_by_role('button',name='Object 1 · right',exact=True)).to_be_visible()
    page.screenshot(path='/tmp/montessori-toddler-transfer.png',full_page=True)
    page.get_by_role('button',name='Back to the classroom').click()
    expect(page.get_by_label('YOUR LEARNING ENVIRONMENT')).to_have_value('18m-3y')
    page.locator('.material-card.shape-puzzle').click()
    page.get_by_role('button',name='Begin the activity').click()
    for shape in ['circle','square','triangle']:page.get_by_role('button',name=f'Lift {shape}',exact=True).click()
    page.get_by_role('button',name='Select circle',exact=True).click()
    page.get_by_role('button',name='Try square opening',exact=True).click()
    expect(page.get_by_text('The outlines are different. Compare another opening.')).to_be_visible()
    page.get_by_role('button',name='3D',exact=True).click()
    expect(page.locator('.activity-stage canvas')).to_be_visible(timeout=15000)
    for shape in ['circle','square','triangle']:
        page.get_by_role('button',name=f'Select {shape}',exact=True).click()
        page.get_by_role('button',name=f'Try {shape} opening',exact=True).click()
    expect(page.get_by_role('status')).to_contain_text('Each shape is back')
    page.screenshot(path='/tmp/montessori-toddler-puzzle.png',full_page=True)
    page.get_by_role('button',name='Back to the classroom').click()
    page.get_by_label('YOUR LEARNING ENVIRONMENT').select_option('3-6y')
    expect(page.locator('.material-card')).to_have_count(5)
    # Dedicated school route from the production artifact, including reload.
    entry=browser.new_page(viewport={'width':1280,'height':1000})
    entry.on('pageerror',lambda e:errors.append(e.stack))
    url='http://127.0.0.1:4173/montessori-virtual-room/school/greenwood/'
    response=entry.goto(url,wait_until='networkidle')
    assert response.status==200
    expect(entry.get_by_role('heading',name='A little closer')).to_be_visible()
    entry.screenshot(path='/tmp/montessori-school-access.png',full_page=True)
    entry.get_by_label('School access code',exact=True).fill('wrong')
    entry.get_by_role('button',name='Enter the classroom').click()
    expect(entry.get_by_role('alert')).to_contain_text('does not match')
    entry.get_by_label('School access code',exact=True).fill('GREENWOOD')
    entry.get_by_role('button',name='Enter the classroom').click()
    expect(entry.get_by_role('heading',name='A room for curiosity.')).to_be_visible()
    expect(entry.get_by_role('button',name='Forget this device')).to_be_visible()
    entry.reload(wait_until='networkidle')
    expect(entry.get_by_role('heading',name='A room for curiosity.')).to_be_visible()
    entry.get_by_role('button',name='Forget this device').click()
    expect(entry.get_by_label('School access code',exact=True)).to_be_visible()
    entry.get_by_label('Remember access on this device').uncheck()
    entry.get_by_label('School access code',exact=True).fill('GREENWOOD')
    entry.get_by_role('button',name='Enter the classroom').click()
    expect(entry.get_by_role('heading',name='A room for curiosity.')).to_be_visible()
    entry.reload(wait_until='networkidle')
    expect(entry.get_by_label('School access code',exact=True)).to_be_visible()
    mobile=browser.new_page(viewport={'width':390,'height':844},is_mobile=True,has_touch=True)
    mobile.on('pageerror',lambda e:errors.append(e.stack))
    mobile.goto('http://127.0.0.1:5173/',wait_until='networkidle')
    mobile.get_by_label('YOUR LEARNING ENVIRONMENT').select_option('18m-3y')
    assert mobile.evaluate('document.documentElement.scrollWidth<=innerWidth')
    for id in ['transferring','shape-puzzle']:
        mobile.locator('.material-card.'+id).tap()
        mobile.get_by_role('button',name='Begin the activity').tap()
        assert mobile.evaluate('document.documentElement.scrollWidth<=innerWidth'),id
        mobile.get_by_role('button',name='3D',exact=True).tap()
        expect(mobile.locator('.activity-stage canvas')).to_be_visible(timeout=15000)
        assert mobile.evaluate('document.documentElement.scrollWidth<=innerWidth'),id+'3d'
        mobile.get_by_role('button',name='Back to the classroom').tap()
    mobile.goto('http://127.0.0.1:5173/school/greenwood/',wait_until='networkidle')
    assert mobile.evaluate('document.documentElement.scrollWidth<=innerWidth')
    assert not errors,'\n'.join(errors)
    print('PASS: separate toddler classroom, two new activities in 2D/3D, switching/reset, mobile reflow, school code errors, remembered/forgotten/unremembered access, and direct Pages school route')
    browser.close()
