"""Check optional observations, stale feedback, automatic completion, and reset."""
import os
from playwright.sync_api import sync_playwright,expect
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/snap/bin/chromium'),headless=True,args=['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'])
 page=browser.new_page(viewport={'width':1280,'height':1000},reduced_motion='reduce')
 page.goto(os.environ.get('APP_URL','http://127.0.0.1:8001/'),wait_until='networkidle')
 page.locator('#age-group').select_option('9-12y')
 page.locator('.material-card.fraction-insets').click();page.get_by_role('button',name='Begin the activity').click()
 expect(page.locator('.activity-feedback')).to_have_count(0)
 page.get_by_role('button',name='Check my work',exact=True).click()
 expect(page.locator('.activity-feedback')).to_contain_text('Move smaller equal pieces')
 page.get_by_role('button',name='Choose 1/3 inset',exact=True).click()
 expect(page.locator('.activity-feedback')).to_contain_text('Check again')
 for _ in range(2):page.get_by_role('button',name='Move one 1/3 to comparison',exact=True).click()
 page.get_by_role('button',name='Check my work',exact=True).click()
 expect(page.locator('.activity-feedback')).to_contain_text('beyond the reference')
 page.locator('.activity-heading').screenshot(path='/tmp/montessori-feedback-controls.png')
 page.get_by_role('button',name='Start again',exact=True).click()
 expect(page.locator('.activity-feedback')).to_have_count(0)
 page.get_by_role('button',name='Choose 1/4 inset',exact=True).click()
 for _ in range(2):page.get_by_role('button',name='Move one 1/4 to comparison',exact=True).click()
 expect(page.get_by_role('heading',name='Activity complete',exact=True)).to_be_visible()
 page.locator('.activity-feedback').screenshot(path='/tmp/montessori-feedback-complete.png')
 page.get_by_role('button',name='Return piece 1, 1/4',exact=True).click()
 expect(page.get_by_role('heading',name='Activity complete',exact=True)).to_have_count(0)
 page.get_by_role('button',name='Back to the classroom').click()
 page.locator('#age-group').select_option('3-6y');page.locator('.material-card.cylinder-blocks').click();page.get_by_role('button',name='Begin the activity').click()
 page.get_by_role('button',name='Check my work',exact=True).click()
 expect(page.locator('.activity-feedback')).to_contain_text('10 pieces have not been lifted')
 browser.close()
print('PASS: optional feedback, state-specific explanation, stale-check handling, automatic completion, reset, and original-material support')
